version: '3'

services:
  mongo-test:
    image: mongo
    container_name: mongo-test
    restart: always
    networks:
      - test-network
    ports:
      - '27017:27017'

networks:
  test-network:
    driver: bridge
